apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.9
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
  # cluster level storage configuration and selection
  resources:
    api:
      requests:
          cpu: 25m
          memory: 250Mi
      limits:
        memory: 512Mi
    mgr:
      requests:
          cpu: 50m
          memory: 300Mi
      limits:
        memory: 512Mi
    mon:
      requests:
          cpu: 35m
          memory: 800Mi
      limits:
        memory: 1024Mi
    osd:
      requests:
        cpu: "35m"
        memory: "2048Mi"
      limits:
        memory: "4096Mi"
    rbdmirror:
      requests:
          cpu: 25m
          memory: 250Mi
      limits:
        memory: 512Mi
  storage:
    useAllNodes: false
    useAllDevices: true
    deviceFilter: "^"
    location:
    config:
      metadataDevice:
      # databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      # journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1"
     nodes:
     - name: "node01"
    #   devices:
    #   - name: "sdb"
     - name: "node02"
    #   devices:
    #   - name: "sdb"
     - name: "node03"
    #   devices:
    #   - name: "sdb"
    # - name: "k3os-c"
    #   devices:
    #   - name: "sdb"
    # - name: "k3s-3"
    #   devices:
    #   - name: "sda"
