---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-security-pv
  annotations:
    fluxcd.io/ignore: "true"
spec:
  storageClassName: home
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.200.60
    path: /mnt/unionfs/Media/Security
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-security-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: home
  resources:
    requests:
      storage: 1Mi
