---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    fluxcd.io/automated: true
spec:
  releaseName: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: v1.3.3
  values:
    csi:
      kubeletDirPath: /var/lib/kubelet
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
