apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mergerfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mergerfs-media
spec:
  capacity:
    storage: 1000Ti
  storageClassName: mergerfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mergerfs
    type: DirectoryOrCreate
  claimRef:
    namespace: media-management
    name: mergerfs-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mergerfs-media-pvc
  namespace: media-management
spec:
  storageClassName: mergerfs
  resources:
    requests:
      storage: 1Mi
  accessModes:
    - ReadWriteMany
