apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-server-pv
spec:
  capacity:
    storage: 200Gi
  storageClassName: nfs-server
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/tank/media/
  claimRef:
    namespace: media-management
    name: nfs-media-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-media-pvc
  namespace: media-management
spec:
  storageClassName: nfs-server
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteMany
