---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
  annotations:
    fluxcd.io/ignore: true
spec:
  storageClassName: media
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.1.60
    path: /mnt
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: media-management
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi
