---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas-merged-media-pv
  annotations:
    fluxcd.io/ignore: "false"
spec:
  storageClassName: media
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.200.210
    path: /mnt/Merged-Media
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-merged-media-pvc
  namespace: media-management
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  volumeName: nfs-nas-merged-media-pv
  resources:
    requests:
      storage: 2Mi
