---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
  annotations:
    fluxcd.io/ignore: "true"
spec:
  storageClassName: media
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.200.60
    path: /mnt
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=8192
    - wsize=8192
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: media-management
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  volumeName: nfs-data-pv
  resources:
    requests:
      storage: 2Mi
