apiVersion: v1
kind: PersistentVolume
metadata:
  name: mergerfs-media
  annotations:
    fluxcd.io/ignore: "true"
spec:
  capacity:
    storage: 1000Ti
  storageClassName: mergerfs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mergerfs
    type: DirectoryOrCreate
  claimRef:
    namespace: media-management
    name: mergerfs-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mergerfs-media-pvc
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "true"
spec:
  storageClassName: mergerfs
  resources:
    requests:
      storage: 2Mi
  accessModes:
    - ReadWriteOnce
