---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
#    fluxcd.io/tag.chart-image: semver:~0.
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  helmVersion: v3
  rollback:
    enable: false
  chart:
    git: git@github.com:dcplaya/billimek-charts
    path: charts/home-assistant
    ref: HA-Sidecar
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.113.0.dev20200715
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    socat:
      enabled: false
      image:
        repository: alpine/socat
        tag: 1.7.3.4-r0
      devices:
      - name: zigbee-device
        mountPath: /zigbee
        ip: ser2sock-zigbee.home-automation.svc
        port: 10000
# Mount devices or folders from the host machine. Can be used for USB device mounting.
    hostMounts:
    - name: zha
      hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6120245D-if01-port0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}
#    cmdOverride:
#      enabled: true
#      shellArgs: "zha start && zwave start && python -m homeassistant --config /config"
#    extraVolumes:
#    - name: zha
#      configMap:
#        defaultMode: 0555
#        name: zha                                                               # name of configMap
#        items:
#        - key: zha                                                              # name of data inside configMap
#          path: zha
#    - name: zwave
#      configMap:
#        defaultMode: 0555
#        name: zwave                                                             # name of configMap
#        items:
#        - key: zwave                                                            # name of data inside configMap
#          path: zwave
#    extraVolumeMounts:
#    - name: zha                                                                 # name of extraVolumes associated with it
#      mountPath: /usr/bin/zha
#      subPath: zha
#    - name: zwave                                                               # name of extraVolumes associated with it
#      mountPath: /usr/bin/zwave
#      subPath: zwave
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.4.1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
    monitoring:
      enabled: false
  valueFileSecrets:
  - name: "home-assistant-helm-values"
