---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~2.
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.5.0
    # git: git@github.com:dcplaya/billimek-charts
    # path: charts/home-assistant
    # ref: home-assistant
  values:
    image:
      repository: homeassistant/home-assistant
      tag: dev
      pullPolicy: Always
    usePodSecurityContext: true
    runAsUser: 1000
    fsgroup: 1000
    # extraEnv:
    #   TZ: "America/Los_Angeles"
    #   PUID: "1000"
    #   PGID: "1000"
    persistence:
      enabled: true
      existingClaim: "home-assistant"
      
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: "longhorn"
        skipUninstall: true
        size: 50Gi

    esphome:
      enabled: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"

    hostNetwork: true
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.40.60

    hostMounts:
    - name: zha
      hostPath: "/dev/zigbee"

    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.4.1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      service:
        port: 8080

    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: [
                "true"]}
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"
    monitoring:
      enabled: false
  valueFileSecrets:
  - name: "home-assistant-helm-values"

