---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: semver:~0.
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  helmVersion: v3
  rollback:
    enable: true
  chart:
    git: git@github.com:dcplaya/billimek-chart
    path: charts/home-assistant
    ref: master
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.112.4
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    socat:
      enabled: true
      arguments: ["pty,link=/dev/ttyUSB0,raw,user=0,group=0,mode=777", "tcp:ser2sock.home-automation.svc:10000"]
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    vscode:
      enabled: false
      image:
        repository: codercom/code-server
        tag: 3.1.1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
    monitoring:
      enabled: false
  valueFileSecrets:
  - name: "home-assistant-helm-values"
