---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hass-postgresql
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: semver:~12
spec:
  releaseName: hass-postgresql
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: postgresql
    version: 9.1.1
  values:
    image:
      repository: postgres
      tag: '12.3'
    postgresqlDataDir: "/data/pgdata"
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    persistence:
      enabled: true
      storageClass: longhorn
      mountPath: "/data/"
      size: 50Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    volumePermissions:
      enabled: true
    # master:
    #   tolerations:
    #   - key: "arm"
    #     operator: "Exists"
  valueFileSecrets:
  - name: "postgresql-helm-values"
