---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi-video
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: true
    fluxcd.io/automated: false
#    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: unifi-video
  helmVersion: v3
  rollback:
    enable: false
  chart:
    git: git@github.com:dcplaya/billimek-charts
    path: charts/unifi-video
    ref: unifi-video
  values:
    replicaCount: 1
    image:
      repository: pducharme/unifi-video-controller
      tag: latest
    persistence:
      config:
        enabled: true
        size: 5Gi
        storageClass: rook-ceph-block
      data:
        enabled: true
        existingClaim: nfs-security-pvc
        storageClass: home
        subPath: Unifi-Video
#      extraExistingClaimMounts:
#        - name: home
#          existingClaim: nfs-security-pvc
#          mountPath: "/mnt/unionfs"
#          readOnly: false
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.40.20
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-video-svc
    timezone: "America/Los_Angeles"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: unifi-data
#    resources:
#      limits:
#        memory: 750Mi
#      requests:
#        cpu: 100m
#        memory: 128Mi
  valueFileSecrets:
  - name: "unifi-video-helm-values"
