---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: "regexp:amd64*"
spec:
  releaseName: tautulli
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: tautulli
    version: 2.2.0
  values:
    image:
      repository: linuxserver/tautulli
      tag: amd64-cb577c51-ls9
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 20Gi
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
  valueFileSecrets:
  - name: "tautulli-helm-values"
