---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
#    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: tautulli
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: tautulli
    version: 4.0.2
  values:
    tautulli:
      image:
        organization: linuxserver
        repository: tautulli
        tag: amd64-develop
        pullPolicy: Always
      ingress:
        enabled: true
        labels:
          app.kubernetes.io/catagory: "media"
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Los_Angeles"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: config-tautulli
        media:
          enabled: false
      # additionalVolumes:
        # - name: nfs-media
          # persistentVolumeClaim:
            # claimName: nfs-nas-merged-media-pvc
      # additionalVolumeMounts:
        # - name: nfs-media
          # mountPath: "/mnt/unionfs"
          # subPath:
      resources:
        requests:
          memory: 451Mi
          cpu: 250m
        limits:
          memory: 500Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "tautulli-helm-values"
