apiVersion: v1
kind: Service
metadata:
  labels:
    app: mc-ecms-minecraft
  name: mc-ecms-minecraft-geyser
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  loadBalancerIP: 10.0.6.104
  ports:
  - name: geyser
    port: 19132
    protocol: UDP
    targetPort: geyser
  selector:
    app: mc-ecms-minecraft
  type: LoadBalancer
