---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: vernemq
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://vernemq.github.io/docker-vernemq
    name: vernemq
    version: 1.6.2
  values:
    image:
      repository: vernemq/vernemq
      tag: 1.10.2-1-alpine
    replicaCount: 1
    serviceMonitor:
      create: true
    podAnnotations:
      backup.velero.io/backup-volumes: data
    persistentVolume:
      enabled: true
      accessModes: ReadWriteOnce
      size: 5Gi
      storageClass: rook-ceph-block
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.40.10
      mqtt:
        enabled: true
        port: 1883                                                              # Default port. Here for visability
      mqtts:
        enabled: false                                                          # Disabled, too much work to get cert inside pod
        port: 8883                                                              # Default port. Here for visability
      ws:
        enabled: true
        port: 8080                                                              # Default port. Here for visability
    statefulset:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
    additionalEnv:
      - name: DOCKER_VERNEMQ_ACCEPT_EULA
        value: "yes"
      - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
        value: "on"
