---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metac
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
#    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: metac
  helmVersion: v3
  rollback:
    enable: true
  chart:
#    repository: https://k8s-at-home.com/charts/
#    name: metac
#    version: 0.1.0
    git: git@github.com:AmitKumarDas/metac
    path: helm/metac
    ref: master
  values:
    image:
      repository: quay.io/amitkumardas/metac
      tag: latest
    discoveryInterval: 10s
    cacheFlushInterval: 24h
    workerCount: 5
    logLevel: 1
    clientGoQps: 5
    clientGoBurst: 10
    resources:
      limits:
        cpu: 80m
        memory: 80Mi
      requests:
        cpu: 50m
        memory: 60Mi
