---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: plex
    version: 1.7.1
#    git: git@github.com:dcplaya/billimek-charts
#    path: charts/nzbget
#    ref: master
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.5.3112-b23ab3896
    hostNetwork: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.20
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.20
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
    persistence:
      transcode:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 30Gi
      data:
        enabled: false
      extraMounts:
      - name: media
        storageClass: media
        claimName: nfs-media-pvc
        mountPath: mnt/unionfs
      config:
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 301Gi
    # Probes configuration
    probes:
      liveness:
        initialDelaySeconds: 60
        failureThreshold: 30
        timeoutSeconds: 15
      readiness:
        initialDelaySeconds: 60
        failureThreshold: 30
        timeoutSeconds: 15
    resources:
      limits:
#        gpu.intel.com/i915: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/plex
              operator: In
              values:
              - "true"
  valueFileSecrets:
  - name: "plex-helm-values"
