---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: media-management
  name: plex-auto-collections
  annotations:
    fluxcd.io/ignored: "false"
    fluxcd.io/automated: "true"
spec:
  # Run once a day, every day, starting at 6PM
  schedule: "0 18 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: plex-auto-collections
            image: burkasaurusrex/plex-auto-collections:latest
            imagePullPolicy: Always
            command: ["python3"]
            args: ["/app/plex_auto_collections.py"]
            # env:
            #   - name: PUID
            #     value: "1000"
            #   - name: GUID
            #     value: "1000"
            #   - name: CLOUDPLOW_CONFIG
            #     value: "/volume1/Media/config/cloudplow/config.json"
            #   - name: CLOUDPLOW_LOGFILE
            #     value: "/volume1/Media/config/cloudplow/cloudplow.log"
            #   - name: CLOUDPLOW_LOGLEVEL
            #     value: "INFO"
            #   - name: CLOUDPLOW_CACHEFILE
            #     value: "/volume1/Media/config/cloudplow/cache.db"
            #   - name: TZ
            #     value: "America/New_York"
            volumeMounts:
            - mountPath: /config
              name: config-plex-auto-collection
            resources:
              requests:
                memory: 50Mi
                cpu: 100m
              limits:
                memory: 200Mi
                cpu: 300m
          restartPolicy: Never
          volumes:
          - name: config-plex-auto-collection
            persistentVolumeClaim:
              claimName: config-plex-auto-collection
    