---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
#    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.2
#    git: git@github.com:dcplaya/billimek-charts
#    path: charts/nzbget
#    ref: master
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.20.1.3252-a78fef9a9
    hostNetwork: true

    ## Set the IDs for proper NAS sharing
    plexUid: 1000
    plexGid: 100

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    changeConfigDirOwnership: true
    serviceTCP:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.20
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.20
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc

    persistence:
      transcode:
        enabled: false
      data:
        enabled: false
      extraMounts:
      - name: media
        storageClass: media
        claimName: nfs-nas-merged-media-pvc
        mountPath: mnt/unionfs
      config:
        claimName: config-plex
        # subPath:
        # storageClass: longhorn
        # accessMode: ReadWriteOnce
        # size: 300Gi
        # skipUninstall: true

    # Probes configuration
    probes:
      liveness:
        initialDelaySeconds: 60
        failureThreshold: 30
        timeoutSeconds: 15
      readiness:
        initialDelaySeconds: 60
        failureThreshold: 30
        timeoutSeconds: 15
    resources:
      limits:
        gpu.intel.com/i915: 1
        memory: 12000Mi
      requests:
        cpu: 35m
        memory: 1500Mi

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - nzbget
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - nzbget
                - sonarr
                - radarr
                - bazarr
            topologyKey: "kubernetes.io/hostname"

  valueFileSecrets:
  - name: "plex-helm-values"
