---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: plex
    version: 1.0.0
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.4.2902-69560ce1e
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.20
    persistence:
      transcode:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
      data:
        enabled: true
        claimName: nfs-media-pvc
      config:
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 150Gi
    resources:
      limits:
        gpu.intel.com/i915: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
  valueFileSecrets:
  - name: "plex-helm-values"
