---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: "regexp:amd64*"
spec:
  releaseName: nzbhydra2
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbhydra2
    version: 2.3.0
  values:
    image:
      repository: linuxserver/nzbhydra2
      tag: amd64-latest
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 5Gi
    resources:
      requests:
        memory: 500Mi
        cpu: 25m
      limits:
        memory: 4000Mi
  valueFileSecrets:
  - name: "nzbhydra2-helm-values"
