---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regexp:^(v2\.[0-9]+\.[0-9]+-ls[0-9]+)$
spec:
  releaseName: nzbhydra2
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbhydra2
    version: 3.0.2
  values:
    image:
      repository: linuxserver/nzbhydra2
      tag: v2.29.0-ls16
    ingress:
      enabled: true
      labels:
        app.kubernetes.io/catagory: "media"
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 100
    persistence:
      config:
        enabled: true
        existingClaim: config-nzbhydra2
    resources:
      requests:
        memory: 500Mi
        cpu: 25m
      limits:
        memory: 4000Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "nzbhydra2-helm-values"
