apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-mount-google
spec:
  capacity:
    storage: 1000Ti
  storageClassName: gdrive
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/disks/google
    type: DirectoryOrCreate
  claimRef:
    namespace: media-management
    name: rclone-mount-google
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rclone-mount-google-pvc
  namespace: media-management
spec:
  storageClassName: gdrive
  resources:
    requests:
      storage: 1Mi
  accessModes:
    - ReadWriteOnce
