---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: longhorn
  helmVersion: v3
  chart:
    git: git@github.com:longhorn/longhorn
    ref: master
    path: chart
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
    ingress:
      enabled: true
#      host: longhorn.storage.elcarpenter.com
      annotations:
        kubernetes.io/ingress.class: nginx
  valueFileSecrets:
  - name: "longhorn-helm-values"
