---
apiVersion: networking.k8s.io/v1beta1
kind: Secret
metadata:
  name: longhorn-aws-secret-helm-values
  namespace: longhorn-system
spec:
  valueFileSecrets:
  - name: "longhorn-aws-secret-helm-values"
