---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: longhorn
  helmVersion: v3
  chart:
    git: git@github.com:longhorn/longhorn
    ref: master
    path: chart
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
      backupTarget: s3://longhorn@minio/backups
      backupTargetCredentialSecret: aws-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
  valueFileSecrets:
  - name: "longhorn-helm-values"
