apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: data-nfs-server-pvc
#      - name: nfs-media
#        persistentVolumeClaim:
#          claimName: nfs-media-pvc
#          namespace: media-management
      restartPolicy: Always
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine
        env:
        - name: SHARED_DIRECTORY
          value: /mnt/tank/share
        ports:
          - name: nfs-2049
            containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /mnt/tank/share
            name: nfs-vol
#          - mountPath: /mnt/tank/media
#            name: nfs-media
      nodeSelector:
        node-role.kubernetes.io/nfs: "true"
