apiVersion: v1
kind: Service
metadata:
  name: nfs-server-gdrive
  namespace: kube-system
spec:
  ports:
    - name: nfs-2049
      port: 2049
      targetPort: 2049
      protocol: TCP
  selector:
    role: nfs-server
  type: LoadBalancer
  loadBalancerIP: 10.201.50.200

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-server
  namespace: kube-system
data:
  2049: "kube-system/nfs-server-gdrive:2049"
