apiVersion: v1
kind: Service
metadata:
  name: nfs-server-gdrive
  namespace: kube-system
spec:
  ports:
    - name: nfs-2049
      port: 2049
  selector:
    role: nfs-server
  type: LoadBalancer
  loadBalancerIP: 10.201.50.200
