apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-gdrive-pv
spec:
  capacity:
    storage: 1000Ti
  storageClassName: gdrive
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/disks/google
  claimRef:
    namespace: kube-system
    name: nfs-server-gdrive-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-server-gdrive-pvc
  namespace: kube-system
spec:
  storageClassName: gdrive
  resources:
    requests:
      storage: 2Mi
  accessModes:
    - ReadWriteMany
