---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      volumes:
      - name: nfs-gdrive
        persistentVolumeClaim:
          claimName: nfs-server-gdrive-pvc
#      - name: nfs-media
#        persistentVolumeClaim:
#          claimName: nfs-media-pvc
#          namespace: media-management
      restartPolicy: Always
      containers:
      - name: nfs-server
        image: erichough/nfs-server:2.2.1
        env:
        - name: NFS_EXPORT_0
          value: "/mnt/disks/google   *(rw,sync,fsid=1,no_subtree_check,all_squash,anonuid=1000,anongid=1000)"
        ports:
        - name: nfs-2049
          containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt/disks/google
          name: nfs-gdrive
#          - mountPath: /mnt/tank/media
#            name: nfs-media
## Make this a podAffinity based on rclone_mount pods
#      nodeSelector:
#        node-role.kubernetes.io/nfs: "true"
