apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-pv
spec:
  capacity:
    storage: 200Gi
  storageClassName: nfs-server
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/tank/share
  claimRef:
    namespace: kube-system
    name: data-nfs-server-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-nfs-server-pvc
  namespace: kube-system
spec:
  storageClassName: nfs-server
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteMany
