---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
#    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9])$'
spec:
  releaseName: node-red
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: node-red
    version: 3.0.0
  values:
    image:
      repository: nodered/node-red
      tag: latest
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      skipUninstall: true
    tolerations:
    - key: "arm"
      operator: "Exists"
    flows: "flows.json"
    enableProjects: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "node-red-helm-values"
