apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: metallb
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    configInline:
      peers:
      - peer-address: 10.10.200.1
        peer-asn: 64512
        my-asn: 64512
      address-pools:
      - name: bgp
        protocol: bgp
        addresses:
        -  10.201.1.0/16
        avoid-buggy-ips: true
    prometheus:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      image:
        repository: metallb/controller
        tag: main
      tolerations:
      - key: "arm"
        operator: "Exists"
    speaker:
      image:
        repository: metallb/speaker
        tag: main
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "armhf"
        operator: "Exists"
