################################################################################
# Ser2Socket is a serial-to-TCP/IP gateway.
# Could be useful for Home Assistant devices
################################################################################
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ser2sock-zigbee
  namespace: home-assistant
spec:
  releaseName: ser2sock-zigbee
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: ser2sock
    version: 1.0.2
  values:
    image:
      repository: tenstartups/ser2sock
      tag: latest
      imagePullPolicy: Always
    timezone: "America/Los_Angeles"
    device: "/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_813004F4-if01-port0"
    tolerations:
    - key: "arm"
      operator: "Exists"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}
    resources:
      requests:
        memory: 50Mi
        cpu: 15m
      limits:
        memory: 250Mi
