---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: network-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(5\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: unifi
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: unifi
    version: 0.10.0
  values:
    image:
      repository: jacobalberty/unifi
      tag: 5.14.22
    persistence:
      enabled: true
      size: 20Gi
      storageClass: longhorn
    timezone: "America/Los_Angeles"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    unifiedService:
      enabled: false
      type: LoadBalancer
      loadBalancerIP: 10.201.90.10
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    guiService:
      type: LoadBalancer
      loadBalancerIP: 10.201.90.10
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    captivePortalService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 10.201.90.11
#      annotations:
#        metallb.universe.tf/allow-shared-ip: unifi
      ingress:
        enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
#        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.201.90.10
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.201.90.10
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.201.90.10
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valueFileSecrets:
  - name: "unifi-helm-values"
