---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
  annotations:
    fluxcd.io/automated: false
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: frigate
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: frigate
    version: 3.0.0
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.5.0
    #   pullPolicy: Always
    coral:
      enabled: true
    config: |
      web_port: 5000
      mqtt:
        host: vernemq.default.svc
        topic_prefix: frigate
      objects:
        track:
          - person
          - dog
          - cat
        filters:
          person:
            min_area: 2500
            max_area: 100000
            threshold: 0.85
          dog:
            min_area: 1000
            max_area: 10000
            threshold: 0.85
          cat:
            min_area: 1000
            max_area: 10000
            threshold: 0.85
      cameras:
        porch:
          ffmpeg:
            input: rtsp://view:{FRIGATE_RTSP_PASSWORD}@porch:554/cam/realmonitor?channel=1&subtype=1
          snapshots:
            show_timestamp: false
          height: 480
          width: 704
          take_frame: 1
          fps: 5
          objects:
            filters:
              person:
                min_area: 1500
                max_area: 100000
                threshold: 0.95
          # regions:
          #   - size: 480
          #     x_offset: 224
          #     y_offset: 0
          #   - size: 480
          #     x_offset: 0
          #     y_offset: 0
        front:
          ffmpeg:
            input: rtsp://view:{FRIGATE_RTSP_PASSWORD}@front:554/cam/realmonitor?channel=1&subtype=1
          snapshots:
            show_timestamp: false
          height: 480
          width: 704
          take_frame: 1
          fps: 5
          # regions:
          #   - size: 480
          #     x_offset: 224
          #     y_offset: 0
          #   - size: 480
          #     x_offset: 0
          #     y_offset: 0
        driveway:
          ffmpeg:
            input: rtsp://view:{FRIGATE_RTSP_PASSWORD}@driveway:554/cam/realmonitor?channel=1&subtype=1
          snapshots:
            show_timestamp: false
          height: 480
          width: 704
          take_frame: 1
          fps: 5
          # regions:
          #   - size: 480
          #     x_offset: 224
          #     y_offset: 0
          #   - size: 480
          #     x_offset: 0
          #     y_offset: 0
        pool:
          ffmpeg:
            input: rtsp://view:{FRIGATE_RTSP_PASSWORD}@pool:554/cam/realmonitor?channel=1&subtype=1
          snapshots:
            show_timestamp: false
          height: 480
          width: 704
          take_frame: 1
          fps: 5
          objects:
            filters:
              person:
                min_area: 1000
                max_area: 100000
                threshold: 0.85
          # regions:
          #   - size: 480
          #     x_offset: 224
          #     y_offset: 0
          #   - size: 480
          #     x_offset: 0
          #     y_offset: 0
        basement:
          ffmpeg:
            input: rtsp://view:{FRIGATE_RTSP_PASSWORD}@basement:554/h264Preview_01_sub
          snapshots:
            show_timestamp: false
          height: 352
          width: 640
          take_frame: 1
          fps: 5
          # regions:
          #   - size: 352
          #     x_offset: 0
          #     y_offset: 0
          #   - size: 352
          #     x_offset: 288
          #     y_offset: 0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tpu
              operator: In
              values:
              - google-coral
    resources:
      requests:
        memory: 1000Mi
        cpu: 750m
      limits:
        memory: 2500Mi
        # gpu.intel.com/i915: 1
  valueFileSecrets:
  - name: "frigate-helm-values"
