---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/ignore: "false"
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: frigate
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: frigate
    version: 4.0.1
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.6.0
      pullPolicy: Always
    coral:
      enabled: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"

    resources:
      requests:
        memory: 1000Mi
        cpu: 750m
      limits:
        memory: 2500Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tpu
              operator: In
              values:
              - google-coral
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"

  valueFileSecrets:
  - name: "frigate-helm-values"
