---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 7.2.0
  values:
    sonarr:
      image:
        organization: hotio
        repository: sonarr
        tag: nightly
      ingress:
        enabled: true
        labels:
          app.kubernetes.io/catagory: "media"
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Los_Angeles"
        PUID: "1000"
        PGID: "100"
      controllerType: statefulset
      persistence:
        config:
          enabled: true
          existingClaim: config-sonarr
        media:
          enabled: false
      additionalVolumes:
        - name: nfs-nas-merged-media-pvc
          persistentVolumeClaim:
            claimName: nfs-nas-merged-media-pvc
      additionalVolumeMounts:
        - name: nfs-nas-merged-media-pvc
          mountPath: "/mnt/unionfs"
          # subPath:
      resources:
        requests:
          memory: 450Mi
          cpu: 250m
        limits:
          memory: 2501Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "sonarr-helm-values"
