---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 3.2.0
  values:
    image:
      repository: linuxserver/sonarr
      tag: 3.0.3.731-ls186
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    uid: 1000
    gid: 1000
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 12Gi
      downloads:
        enabled: false
      tv:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: "/mnt/unionfs"
          readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    tolerations:
    - key: "arm"
      operator: "Exists"
  valueFileSecrets:
  - name: "sonarr-helm-values"
