---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: false
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 4.1.3
  values:
    image:
      repository: linuxserver/sonarr
      tag: 3.0.3.905-ls35
    ingress:
      enabled: true
      labels:
        app.kubernetes.io/catagory: "media"
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 25Gi
      media:
        enabled: false
      extraExistingClaimMounts:
        - name: nfs-media
          existingClaim: nfs-media-pvc
          mountPath: "/mnt/unionfs"
          readOnly: false
    resources:
      requests:
        memory: 450Mi
        cpu: 250m
      limits:
        memory: 1500Mi
  valueFileSecrets:
  - name: "sonarr-helm-values"
