---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 6.0.0
  sonarr:
    image:
      repository: linuxserver/sonarr
      tag: 3.0.3.905-ls35
    ingress:
      enabled: true
      labels:
        app.kubernetes.io/catagory: "media"
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Los_Angeles"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    persistence:
      type: statefulset
      config:
        enabled: true
        storageClass: longhorn
        size: 25Gi
        skipUninstall: true
      media:
        enabled: false
      additionalVolumes:
        - name: nfs-media
          mountPath: "/mnt/unionfs"
          # subPath:
      additionalVolumeMounts:
        - name: nfs-media
          existingClaim: nfs-nas-merged-media-pvc
    resources:
      requests:
        memory: 450Mi
        cpu: 250m
      limits:
        memory: 2500Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "sonarr-helm-values"
