---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: modem-stats
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: true
spec:
  releaseName: modem-stats
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: modem-stats
    version: 2.0.0
  values:
    image:
      repository: billimek/sb6183-for-influxdb
      tag: latest
    debug: true
    config:
        delay: 600
        influxdb:
            host: influxdb
            port: 8086
            database: cable_modem_stats
