#createCRD: false
git:
  ssh:
    secretName: flux-git-deploy
chartsSyncInterval: "1m"
statusUpdateInterval: "1m"
helm:
  versions: "v3"
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
