---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 1.0.2
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/dcplaya/k8s-gitops/master/cluster/flux/helm-operator/flux-helm-operator-values.yaml
