---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: longhorn-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:RELEASE*
spec:
  releaseName: minio
  helmVersion: v3
  chart:
    repository: https://helm.min.io/
    name: minio
    version: 7.0.0
  values:
    image:
      repository: minio/minio
      tag: RELEASE.2020-09-17T04-49-20Z
      pullPolicy: Always
    mcImage:
      repository: minio/mc
      tag: RELEASE.2020-08-08T02-33-58Z
      pullPolicy: Always
    helmKubectlJqImage:
      repository: bskim45/helm-kubectl-jq
      tag: 3.3.0
    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 100
    persistence:
      existingClaim: "nfs-backup-longhorn-pvc"
      storageClass: "backup"
      subPath: "longhorn/minio"

    metrics:
      serviceMonitor:
        enabled: true

    nasgateway:
      enabled: true
      # Number of parallel instances
      replicas: 3

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx

    readinessProbe:
      initialDelaySeconds: 10

    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    metrics:
      serviceMonitor:
        enabled: true
  valueFileSecrets:
  - name: "minio-longhorn-helm-values"
