---
- include: basics.yml
# - include: user.yml
# - include: firewall.yml
- include: network.yml

## Used for Longhorn devices. I like Longhorn so I am not making this a configurable option
- include: multipath.yml