---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: false
spec:
  releaseName: velero
  chart:
    repository: https://vmware-tanzu.github.io/helm-charts
    name: velero
    version: 2.12.0
  values:
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: false
    deployRestic: true
    # installCRDs: false
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
      - key: "arm"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 2000Mi
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "120h"
  valueFileSecrets:
  - name: "velero-helm-values"
