apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: keycloak
  chart:
    repository: https://codecentric.github.io/helm-charts
    name: keycloak
    version: 7.3.0
  values:
    keycloak:
      replicas: 3
      username: keycloak
      persistence:
        deployPostgres: true
        storageClass: rook-ceph-block
        dbVendor: postgres
      extraArgs: -Dkeycloak.import=/realm/realm.json
      extraVolumes: |
        - name: keycloak-realm
          secret:
            secretName: keycloak-realm
      extraVolumeMounts: |
        - name: keycloak-realm
          mountPath: "/realm/"
          readOnly: true
  valueFileSecrets:
    - name: "keycloak-helm-values"
