apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgA++TbxUojSL4njS3bAi89i3KllU/Ui9OvISyslySHElOq4+95uFRurbf8xbJiz3b+w7ScvxNRuZv7nM9tLA8AUvpD4pc/arlUl1rIAtAByAnikpICtIPQ9fUEmmNYkcusS8npi+oRikxqyV4psZIcpiJVXzp65gGB2/qovExXqtJGsnrHkuovk4hiykxDmOrbJZnfKNj6m8I878VRU+eSVXcC9LeG6Zt18G57b8KZuw0Fk7/YynZOvpVtZQGD7StzvBQ1tDMoltitQbFnAaWdgIK9PK9D5KksTFRn/3Ff/NIwEdE/R4HU51R/MIHzHET8lIq+6I2FfEN1e0emxqPwHY3WfD+X4LrYrKlQef+kQV2RL6AhaKGL2qxdakrAwspqKd6sLdMem5TQvNTOxh/YNlxvCzaVqqJVIioC/fIeIgh4bo4KqVBPJesnQOd5loJXB2JyCu7rTiBSZ5j01Dls5ZUdSSDr+YW0RIcDsgekYwzFDcSV7axad5La2znc6F1yuq63hhDm+2c2rzN2q8X0zm/h2wpZ2eqJH4uOCzerQQUl8uhbHAjotnUSEbjf8gTG5J97uosj/eODIvxSAS50i/rU4fzW6aK+ntFQD5/WKAYF6XLGfpr8b4WmmLvAQGs3nk3LWYlIjM5MPgvg+Wz64XRvcced8GcQf0FjMAaLQl4+hzPWKczHFcVYbhx3ytS5tgtu9+MnBzDywXg3NY2fAkmFhAlh7QaUHNzaNaX+lHscBYj7x3x1T47J/GBSoIEaHFw3K0rMlBJGylL2L/CkuIm1rSi3q1yT5jcpx3CdWYWd+Ev94BBWJCyc+t6KsLdT0anpcDOA8rE5WuMDS2EPj+VM9SBvzOLhSj2OxLx02CYtR5BD6Mzq7
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-helm-values
      namespace: kube-system
status: {}
