---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v4.[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: ombi
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: ombi
    version: 4.0.0
  values:
    ombi:
      image:
        repository: linuxserver/ombi
        tag: arm32v7-v4-preview
      ## Ingress is located in the helm-template (secrets) file now
      env:
        TZ: "America/Los_Angeles"
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      persistence:
        type: statefulset
        config:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 5Gi
          skipUninstall: true
        media:
          enabled: false
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 2000Mi
          cpu: 1000m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - plex
              topologyKey: "kubernetes.io/hostname"
      valueFileSecrets:
      - name: "ombi-helm-values"
