---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^amd64-(v4.[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: ombi
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: ombi
    version: 4.0.0
  values:
    ombi:
      image:
        organization: linuxserver
        repository: ombi
        tag: v4.0.471-ls10
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Los_Angeles"
        PUID: "1000"
        PGID: "1000"
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: config-ombi
        media:
          enabled: false
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 2000Mi
          cpu: 1000m
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: node-role.kubernetes.io/worker
#                operator: In
#                values:
#                - "true"
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 100
#            podAffinityTerm:
#              labelSelector:
#                matchExpressions:
#                - key: app.kubernetes.io/name
#                  operator: In
#                  values:
#                  - plex
#              topologyKey: "kubernetes.io/hostname"
valueFileSecrets:
- name: "ombi-helm-values"
