---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v4.[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: ombi
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: ombi
    version: 2.2.3
  values:
    image:
      repository: linuxserver/ombi
      tag: v4.0.449-ls8
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 750Mi
        cpu: 1000m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
  valueFileSecrets:
  - name: "ombi-helm-values"
