apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBMNbanMMrNA3VbdMmeds9i7M+394wae0fc/TkLwfYoFO4B5zLUkbdWw5YWKjFLbBMaixIN+1UwvG3Cxz0jgzVzR9ttLBB1pi50cOGzomYos020AnBxwim83RjxSS5uqzIy1MLClig2Ck3zailP3Xi/lHp5hf6aOP21XGedasPOG2y4fwpIRT64uMHJlBeFVbwIuRzM3+6imW9kF+j/1Zg4zP+mDDY1XJ0ZmmqY+MP+dI64zXEXeYnaASrJCxYc/EUO5Ru/zZcztfK5BYOn28xlogikRktDtrABI1Cb9gf4zqt7KR/nYz0B+Oa7G0fPlwdS1W/xmd4XtyW+a8i0MiTC1WG0bmMaeanWO7DhxOxTlhV57RlH/VAzY3/9G+bOPnmb8YptsC1GVrAM9+OdHLoBBKqV2jnndbda95Hyu4nkQRJKxw0BOj6SjgMRgn8RFkELMAIUgGF48EFwhyN6zzaMfCWsBK7a4uWQd9UG4qaz32m936RNiuaqj1r8PMTv2x0PfNYrL121x/ZJ3MgAoNkJYDNPsGm8Wcn92Jh6taacLVt2fUgrhdsRc5haHNMZGcv1Sa2F6gVH1l32vJvoTLWCrRVhqBoCdM9EYIWKx+kmNyzJ9348lB3coXULTsMPO45Deel1X6kVjXfxZBirzKMDOq+sIiPGrRPzqd3xSOXPK2C2IVXOtbtoQLh8RWapYaxvgGMEwuEPQD7txK6zA9XQgPxl
  template:
    metadata:
      creationTimestamp: null
      name: nginx-basic-auth
      namespace: kube-system
status: {}
