---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
#    fluxcd.io/tag.chart-image: 'regexp:^(v[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbget
    version: 3.3.0
#    git: git@github.com:dcplaya/billimek-charts
#    path: charts/nzbget
#    ref: master
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.0-ls61
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      downloads:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 200Gi
      extraMounts:
      - name: "media"
        storageClass: media
        claimName: nfs-media-pvc
        mountPath: mnt/unionfs
      config:
        enabled: true
        storageClass: "longhorn"
        size: 50Mi
    tolerations:
    resources:
      requests:
        memory: 1000Mi
        cpu: 250m
      limits:
        memory: 6000Mi
  valueFileSecrets:
  - name: "nzbget-helm-values"
