---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v21\.0-ls[0-9]+)$'
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 4.0.1
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.0-ls61
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.70.10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 100
    persistence:
      downloads:
        enabled: false
        storageClass: longhorn
        size: 200Gi
      config:
        enabled: true
        existingClaim: config-nzbget
      extraMounts:
      - name: "nfs-media"
        storageClass: media
        claimName: nfs-nas-merged-media-pvc
        mountPath: mnt/unionfs
    tolerations:
    resources:
      requests:
        memory: 1000Mi
        cpu: 250m
      limits:
        memory: 6000Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "nzbget-helm-values"
