---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 4.1.3
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.0.2719-ls1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 12Gi
      media:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: "/mnt/unionfs"
          readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "radarr-helm-values"
