---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: autoscan
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
#    fluxcd.io/tag.chart-image: 'regexp:^stable-(v0.[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: autoscan
  rollback:
    enable: true
  chart:
    # repository: https://k8s-at-home.com/charts/
    # name: autoscan
    # version: 1.0.0
    git: git@github.com:dcplaya/charts
    path: charts/autoscan
    ref: autoscan
  values:
    autoscan:
      image:
        organization: cloudb0x
        repository: autoscan
        tag: latest
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      configPath: /config
      env:
        TZ: "America/Los_Angeles"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: config-autoscan
        media:
          enabled: false
      additionalVolumes:
        - name: nfs-nas-merged-media-pvc
          persistentVolumeClaim:
            claimName: nfs-nas-merged-media-pvc
      additionalVolumeMounts:
        - name: nfs-nas-merged-media-pvc
          mountPath: "/mnt/unionfs"
          # subPath:
      resources:
        requests:
          memory: 350Mi
          cpu: 26m
        limits:
          memory: 2000Mi
          cpu: 1000m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "autoscan-helm-values"
