---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:0.9
spec:
  releaseName: bazarr
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: bazarr
    version: 3.1.0
  values:
    image:
      repository: linuxserver/bazarr
      tag: v0.9.0.2-ls89
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 100
    persistence:
      config:
        enabled: true
        existingClaim: config-bazarr
      media:
        enabled: false
      extraExistingClaimMounts:
      - name: nfs-media
        existingClaim: nfs-nas-merged-media-pvc
        mountPath: /mnt/unionfs
        readOnly: false
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 400Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "bazarr-helm-values"
