---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
    fluxcd.io/tag.chart-image: semver:0.8
spec:
  releaseName: bazarr
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: bazarr
    version: 2.0.2
  values:
    image:
      repository: linuxserver/bazarr
      tag: v0.8.4.3-ls74
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        enabled: false
      extraExistingClaimMounts:
      - name: nfs-media
        existingClaim: nfs-media-pvc
        mountPath: /mnt/unionfs
        readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 4000Mi
  valueFileSecrets:
  - name: "bazarr-helm-values"
