---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: librespeed
  namespace: network-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
#    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9])$'
spec:
  releaseName: librespeed
  helmVersion: v3
  rollback:
    enable: true
  chart:
#    repository: https://billimek.com/billimek-charts/
#    name: node-red
#    version: 2.0.1
    git: git@github.com:dcplaya/billimek-charts
    path: charts/librespeed
    ref: librespeed
  values:
    image:
      repository: adolfintel/speedtest
      tag: latest
    persistence:
      enabled: true
      storageClass: longhorn
      size: 1Gi
    timezone: America/Los_Angeles
    puid: "1000"
    pgid: "1000"
    telemetry: "true"
    title: "Ludicrous Speedtest"
    email: "fake@fake.com"
    tolerations:
    - key: "arm"
      operator: "Exists"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "librespeed-helm-values"
