---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
#    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: esphome
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: esphome
    version: 2.0.0
#    git: git@github.com:dcplaya/billimek-charts
#    path: charts/esphome
#    ref: master
  values:
    image:
      repository: esphome/esphome
      tag: 'd97a9bf'
    extraEnv:
      ESPHOME_DASHBOARD_USE_PING: "true"
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    service:
      port: 6052
      loadBalancerIP: 10.201.40.50
    persistence:
      enabled: true
      storageClass: longhorn                                                    # Use Default
      accessMode: ReadWriteOnce
      size: 10Gi
      skipUninstall: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    resources:
      requests:
        memory: 1000Mi
        cpu: 750m
      limits:
        memory: 2500Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "esphome-helm-values"
