---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
    namespace: velero
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: false
    fluxcd.io/tag.chart-image: glob:RELEASE.*
spec:
  releaseName: minio
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 5.0.27
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2020-04-23T00-58-49Z
    mcImage:
      repository: jessestuart/mc
      tag: RELEASE.2020-04-17T08-55-48Z
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    persistence:
      existingClaim: "nfs-backup-pvc"
      subPath: "kubernetes/velero/minio"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: false
  valueFileSecrets:
  - name: "minio-helm-values"
