apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifs-media-pv
spec:
  capacity:
    storage: 1.5Ti
  storageClassName: media
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "fstab/cifs"
    secretRef:
      name: cifs-secret-test
    options:
      source: "//10.10.200.210/Media/mergerFS"
      mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cifs-media-pvc
  namespace: media-management
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi
  volumeName: cifs-media-pv
