apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifs-media-pv
  annotations:
    fluxcd.io/ignore: "true"
spec:
  capacity:
    storage: 1.5Ti
  storageClassName: media
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: juliohm/cifs
    options:
      opts: sec=ntlm,uid=1000
      server: 10.10.200.210
      share: /Media/mergerFS
    secretRef:
      name: cifs-secret-test

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cifs-media-pvc
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi
  volumeName: cifs-media-pv
