---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vscode
  namespace: devops
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
#    fluxcd.io/tag.chart-image: 'regexp:^stable-(v0.[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: vscode
  rollback:
    enable: true
  chart:
    # repository: https://k8s-at-home.com/charts/
    # name: vscode
    # version: 1.0.0
    git: git@github.com:dcplaya/charts
    path: charts/code-server
    ref: vscode
  values:
    vscode:
      image:
        organization: linuxserver
        repository: code-server
        tag: v3.5.0-ls48
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      configPath: /config
      env:
        TZ: "America/Los_Angeles"
        PUID: "1000"
        PGID: "100"
        PASSWORD: "temp123"
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: config-vscode
        media:
          enabled: false
      # additionalVolumes:
      #   - name: nfs-media
      #     persistentVolumeClaim:
      #       claimName: nfs-nas-merged-media-pvc
      # additionalVolumeMounts:
      #   - name: nfs-media
      #     mountPath: "/mnt/unionfs"
      #     # subPath:
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 2000Mi
          cpu: 1000m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "vscode-helm-values"
