---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: statping
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:0.90
spec:
  releaseName: statping
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: statping
    version: 1.0.0
  values:
    image:
      repository: statping/statping
      tag: v0.90.66
    persistence:
      enabled: true
      exisitingClaim: config-statping
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 35m
        memory: 10Mi
  valueFileSecrets:
  - name: "statping-helm-values"
