---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media-management
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: jellyfin
  rollback:
    enable: false
  chart:
    git: https://github.com/brianmcarey/jellyfin-helm/
    ref: master
    path: /
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.5.2
    # deploymentAnnotations:
    #   stash.appscode.com/backup-blueprint: default-workload-blueprint
    #   stash.appscode.com/target-paths: "/config"
    #   stash.appscode.com/volume-mounts: "config:/config"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Los_Angeles"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 30Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
    # nodeSelector:
    #   app: "nvidia-gpu-plugin"
    resources:
      limits:
        gpu.intel.com/i915: 1
        # nvidia.com/gpu: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
  valueFileSecrets:
  - name: "jellyfin-helm-values"
