apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: descheduler
  rollback:
    enabled: false
  chart:
    # using direct git repo until https://github.com/kubernetes-sigs/descheduler/pull/298 is merged
    git: https://github.com/stevehipwell/descheduler/
    ref: helm-chart
    path: charts/descheduler
  values:
    image:
      repository: us.gcr.io/k8s-artifacts-prod/descheduler/descheduler
      tag: v0.18.0
    schedule: "*/2 * * * *"
    cmdOptions:
      v: 3
      evict-local-storage-pods: ''
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: false
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
            namespaces:
              exclude:
              - "longhorn-system"
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        LowNodeUtilization:
          enabled: true
          params:
            namespaces:
              exclude:
              - "longhorn-system"
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu : 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu : 50
                memory: 50
                pods: 50
