---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hyperion-ng
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
#    fluxcd.io/tag.chart-image: 'regexp:^stable-(v0.[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: hyperion-ng
  rollback:
    enable: true
  chart:
    # repository: https://k8s-at-home.com/charts/
    # name: hyperion
    # version: 1.0.0
    git: git@github.com:dcplaya/charts
    path: charts/hyperion-ng
    ref: hyperion.ng
  values:
    hyperion-ng:
      image:
        organization: sirfragalot
        repository: hyperion.ng
        tag: 2.0.0-alpha.8-x86_64
      ingress:
        enabled: true
        labels:
          app.kubernetes.io/catagory: "home"
        annotations:
          kubernetes.io/ingress.class: "nginx"
      service:
        port: 8090
        # type: LoadBalancer
        # loadBalancerIP: 10.201.40.70
        annotations:
          metallb.universe.tf/allow-shared-ip: hyperion-svc
        additionalSpec:
          ports:
          - name: http
            port: 8090
            protocol: TCP
            targetPort: 8090
          - name: port1
            port: 19445
            protocol: TCP
            targetPort: 19445
          - name: port2
            port: 19444
            protocol: TCP
            targetPort: 19444
      configPath: /root/.hyperion
      env:
        TZ: "America/Los_Angeles"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: config-hyperion-ng
        media:
          enabled: false
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 2000Mi
          cpu: 1000m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "hyperion-ng-helm-values"
