## This will only run the flux/tasks/main.yml (currently flux v2)
## Flux can be run multiple times, it will auto detect if flux is already installed in the cluster and upgrade if needed

---
- hosts: localhost #defines what hosts to install this role one
  gather_facts: yes
  become: no
  roles:
    - { role: flux }