master:
  hosts:
    node00:
      ansible_host: node00.cluster.elcarpenter.com
  vars:
    k3s_control_node: true
    # Gotta figure out what this does
    k3s_tls_san: "node00.cluster.elcarpenter.com"

nodes:
  hosts:
#    node00:
#      ansible_host: node00.cluster.elcarpenter.com
    node01:
      ansible_host: node01.cluster.elcarpenter.com
    node02:
      ansible_host: node02.cluster.elcarpenter.com
    node03:
      ansible_host: node03.cluster.elcarpenter.com
    node04:
      ansible_host: node04.cluster.elcarpenter.com
  vars:

nfs:
  hosts:
#    node00:
#      ansible_host: node00.cluster.elcarpenter.com
    node01:
      ansible_host: node01.cluster.elcarpenter.com
    node02:
      ansible_host: node02.cluster.elcarpenter.com
    node03:
      ansible_host: node03.cluster.elcarpenter.com
    node04:
      ansible_host: node04.cluster.elcarpenter.com
  vars:

longhorn_storage:
  hosts:
#    node00:
#      ansible_host: node00.cluster.elcarpenter.com
    node01:
      ansible_host: node01.cluster.elcarpenter.com
    node02:
      ansible_host: node02.cluster.elcarpenter.com
    node03:
      ansible_host: node03.cluster.elcarpenter.com
    node04:
      ansible_host: node04.cluster.elcarpenter.com
  vars:

# No arm devices yet. Leaving as an example
#arm:
#  hosts:
#    n2-0:
#      ansible_host: n2-0.holthome.net
#  vars:

# This defines what servers should get what services. All servers under master and nodes get the k3s_cluster service as an example
k3s_cluster:
  children:
    master:
    nodes:

storage:
  children:
    nfs:
    longhorn_storage:

vault:
  hosts:
    localhost:
      ansible_connection: local
