---

#################################################################
# Ansible role for installing Rancher Labs k3s ("Lightweight
# Kubernetes") as either a standalone server or cluster.
#################################################################

- hosts: k3s_cluster #defines what hosts to install this role one
  become: true
  vars:
    #k3s_build_cluster: false             #	When multiple play_hosts are available, attempt to cluster.
  roles:
    - { role: xanmanning.k3s }
    - { role: andrewrothstein.calicoctl }
    - { role: andrewrothstein.fluxctl }
