---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: network-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
#    fluxcd.io/tag.chart-image: 'regexp:^(5\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: adguard-home
  helmVersion: v3
  rollback:
    enable: false
  chart:
    git: git@github.com:dcplaya/billimek-charts
    path: charts/adguard-home
    ref: adguard-home
  values:
    image:
      repository: adguard/adguardhome
    tag: latest
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: "rook-ceph-block"
      work:
        enabled: true
        size: 10Gi
        storageClass: "rook-ceph-block"
    timezone: "America/Los_Angeles"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-body-size: 500m
    service:
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceTCP:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceUDP:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceDNSOverTLS:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valueFileSecrets:
  - name: "adguard-home-helm-values"
