---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: network-management
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: true
#    fluxcd.io/tag.chart-image: 'regexp:^(5\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: adguard-home
  helmVersion: v3
  rollback:
    enable: false
  chart:
#    git: git@github.com:dcplaya/billimek-charts
#    path: charts/adguard-home
#    ref: adguard-home
    repository: https://billimek.com/billimek-charts/
    name: adguard-home
    version: 1.0.0
  values:
    image:
      repository: adguard/adguardhome
      tag: beta
    persistence:
      config:
        enabled: true
        size: 10Mi
        storageClass: longhorn
      work:
        enabled: true
        size: 50Gi
        storageClass: longhorn
    timezone: "America/Los_Angeles"
    replicas: 0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    service:
      type: LoadBalancer
#      loadBalancerIP: 10.201.90.20
#      annotations:
#        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceTCP:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceUDP:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceDNSOverTLS:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      loadBalancerIP: 10.201.90.20
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valueFileSecrets:
  - name: "adguard-home-helm-values"
