apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: consul
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  releaseName: consul
  helmVersion: v3
  rollback:
    enabled: true
  chart:
    git: https://github.com/hashicorp/consul-helm
    ref: v0.17.0
    path: .
  values:
    server:
      replicas: 3
      enabled: "true"
      tolerations: |
        - key: "arm"
          operator: "Exists"
      storageClass: nfs
      storage: 10Gi
    client:
      tolerations: |
        - key: "arm"
          operator: "Exists"
