apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: true
  labels:
    app.kubernetes.io/name: consul
spec:
  rules:
  - host: consul.cluster.elcarpenter.com
    http:
      paths:
      - path: /
        backend:
          serviceName: consul-consul-ui
          servicePort: 80
