---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unms
  namespace: network-management
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0.0
spec:
  releaseName: unms
  helmVersion: v3
  rollback:
    enable: true
  chart:
#    git: git@github.com:t3n/helm-charts
#    path: unms
#    ref: master
    git: git@github.com:dcplaya/helm-charts
    path: unms
    ref: unms
  values:
    image:
      repository: ubnt/unms
      tag: 1.2.5
      nginx:
        repository: ubnt/unms-nginx
        tag: 1.2.5
    persistence:
      enabled: true
      size: 10Gi
      storageClass: rook-ceph-block
    timezone: "America/Los_Angeles"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    podAnnotations:
      backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 750Mi
        cpu: 200m
  valueFileSecrets:
  - name: "unms-helm-values"
