apiVersion: v1
kind: ConfigMap
metadata:
  name: nfd-worker-config
  namespace: kube-system
data:
  nfd-worker.conf: |
    sources:
      usb:
        deviceClassWhitelist:
          - "02"
          - "0e"
          - "ef"
          - "fe"
          - "ff"
        deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
      custom:
        - name: "alarmdecoder"
          matchOn:
            - usbId:
                class: ["ff"]
                vendor: ["0403"]
                device: ["6015"]
        - name: "zwave"
          matchOn:
            - usbId:
                class: ["02"]
                vendor: ["0658"]
                device: ["0200"]
        - name: "zigbee"
          matchOn:
            - usbId:
                class: ["ff"]
                vendor: ["10c4"]
                device: ["8a2a"]
        - name: "coral-tpu"
          matchOn:
            - usbId:
                vendor: ["1a6e", "18d1"]
        - name: "intel-gpu"
          matchOn:
            - pciId:
                class: ["0300"]
                vendor: ["8086"]
            - pciId:
                class: ["5916"]
                vendor: ["8086"]
