---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-longhorn-pv
spec:
  storageClassName: backup
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.200.60
    path: /mnt/kubernetes
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=8192
    - wsize=8192
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backup-longhorn-pvc
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: backup
  resources:
    requests:
      storage: 600Gi
