---
- name: Install Flux CLI
  shell: |
    curl -s https://toolkit.fluxcd.io/install.sh | sudo bash

- name: Create flux namespace
  command: "kubectl apply -f {{ REPO_ROOT }}/cluster/flux/namespace.yaml"
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"

- name: Deploy Flux
  shell: |
    flux bootstrap github \
      --owner={{ github_username }} \
      --repository={{ github_k8s_reponame }} \
      --path=cluster \
      --personal \
      --components=source-controller,kustomize-controller,helm-controller,notification-controller \
      --version=latest
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"
    GITHUB_TOKEN: "{{ github_personal_access_token }}"

