helmOperator:
  create: true
git:
  url: "git@github.com:dcplaya/k8s-gitops"
  branch: master
  path: cluster
  user: "dcplaya"
  email: "dcplaya@users.noreply.github.com"
image:
  repository: docker.io/fluxcd/flux
  tag: 1.21.0
memcached:
  tolerations:
  - key: "arm"
    operator: "Exists"
# additionalArgs:
# - --connect=ws://fluxcloud
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
