apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: hubot-helm-values
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  keys:
    - values.yaml
  path: secrets/default/hubot/hubot-helm-values
  type: Opaque
