name: main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Ansible
        uses: ansible/ansible-lint-action@master
        with:
          targets: ./ansible

      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@v3.1.0
        with:
          helmRelease: cluster/
          kubernetesVersion: 1.17.3
          ignoreValues: false
